#ifndef QUELLOG_ZECTRIX_CONFIG_H_
#define QUELLOG_ZECTRIX_CONFIG_H_

#include <driver/gpio.h>

#define QUELLOG_BOOT_BUTTON_GPIO GPIO_NUM_0
#define QUELLOG_UP_BUTTON_GPIO GPIO_NUM_39
#define QUELLOG_DOWN_BUTTON_GPIO GPIO_NUM_18
#define QUELLOG_DISPLAY_WIDTH 400
#define QUELLOG_DISPLAY_HEIGHT 300

#endif  // QUELLOG_ZECTRIX_CONFIG_H_
